### ISSUE TITLE
“look-and-feel” folder should be renamed to “desktoptheme”

### ISSUE THREAD

**Issue by cemetary** [n4n0GH/hello#11]
Since folder `look-and-feel` is actually a desktop theme (leading to confussion), it should be renamed to `desktoptheme`.

**Comment by n4n0GH** [comment]
Agreed. It'll also be modified to only have the "light" theme available as that works incredibly well with dark colorschemes and there's no need to take care of two themes if one also does the job of the other theme. 

16. Nov. 2019, 19:31 von notifications@github.com:

**Comment by cemetary** [comment]
> It'll also be modified to only have the "light" theme available

But what if users want to have light color scheme with dark plasma theme, or vice versa? (Like in my case). :-/

**Comment by n4n0GH** [comment]
Damn you pesky users and your weird usecases :v 

I'll think about how to fix that specific issue.

**Comment by n4n0GH** [comment]
Re-added the dark plasma theme for the time being.
