### ISSUE TITLE
[Plasma theme] [Request] Sharp edge on desktop theme

### ISSUE THREAD

**Issue by cemetary** [n4n0GH/hello#12]
Hi.

I was wondering if you would like to change the edge on desktop theme. I think that ~blur~ drop shadow looks weird when you have maximazed windows. See screenshots below.

| Theme variant |                                                   Screenshot |
| :------------ | -----------------------------------------------------------: |
| hello dark    | ![Screenshot_20191116_142835](https://user-images.githubusercontent.com/10538213/68998864-b78d2100-08af-11ea-94ae-f1523c6b1985.png) |
| hello light   | ![Screenshot_20191116_161412](https://user-images.githubusercontent.com/10538213/68999919-83b9f780-08bf-11ea-981f-dfbb9c1e875c.png) |

***

For reference, check [Amethyst](https://store.kde.org/p/1322963) theme:

![Screenshot_20191116_141133](https://user-images.githubusercontent.com/10538213/68998824-43eb1400-08af-11ea-8ac4-94e282ea7852.png)

**Comment by n4n0GH** [comment]
Absolutely. It's not blur that you're seeing, but the drop shadow from the titlebar. And yes, it's annoying me as well ;-)

**Comment by cemetary** [comment]
Because of my lame English, "blur" was the first word that came up. Ha, ha, ha...

Thanks. :-)

**Comment by n4n0GH** [comment]
So in the case of that Amethyst theme it seems like the background SVG has no shadow at all, which means that no menu pop up will have shadows, but also the panel will be "sharper" when put against a maximized window.

Not a solution I'm fond of, to be honest. I need to get this fixed in a different way.

**Comment by cemetary** [comment]
Oh, now I see. I guess happen the same with [Nordic-kde](https://github.com/EliverLara/Nordic-kde).

Well, thanks for trying.

**Comment by n4n0GH** [comment]
So I noticed something interesting while testing other things: when you force windows to always stay "on top", the shadow of the panel will accurately be below those windows. Maybe it's worth reopening this issue and investigate this as I also don't find the current behaviour to be too pleasing.

**Comment by n4n0GH** [comment]
After some thorough research this is indeed an issue with z-axis layering of the windows. Using Latte Dock as a panel this can be configured and avoided but I don't think there's any chance of getting this done with a Plasma theme alone without completely removing the shadow.
