### ISSUE TITLE
[Plasma theme] hello light variant needs appropriate show desktop icon

### ISSUE THREAD

**Issue by cemetary** [n4n0GH/hello#13]
See screenshot.

![Screenshot_20191116_162335](https://user-images.githubusercontent.com/10538213/69000062-c67ccf00-08c1-11ea-9fbc-c7137f82b6b9.png)

***

Also, please consider make a "show-desktop" icon to make it consistent with theme. :-)

**Comment by n4n0GH** [comment]
Issue is a duplicate of #6 

I'll take the liberty to rename this issue and make it into a feature request for the icon.

**Comment by n4n0GH** [comment]
So apparently that icon is bound to whatever icon set you're currently using. Try it out:

- Select any icon set
- ```plasmashell --replace &```

Closing it for now until I get to fiddle with icon sets owo
