### ISSUE TITLE
[Window decoration] [Request] Custom button colors?

### ISSUE THREAD

**Issue by vllur** [n4n0GH/hello#14]
Hi,
I wonder if it is possible to implement color choosing for control buttons. It would be easier to match hello decorations with custom GTK+ themes.
For example it could be a hex color input in buttons section (at least for the main 3 buttons, and an option to reset to default).

**Comment by n4n0GH** [comment]
Previously I was against that, but I may implement that. 

17. Nov. 2019, 18:57 von notifications@github.com:

**Comment by n4n0GH** [comment]
Done with 75fddc9
