### ISSUE TITLE
[BUG] Window corners rounded when apps are started maximized

### ISSUE THREAD

**Issue by Acemond** [n4n0GH/hello#17]
**Describe the bug**
When some application is started already maximized, its corners are rounded. This also applies when switching virtual desktops and coming back to the desktop where a window is maximized.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. install the rounded corners script
2. start any app, like Firefox
3. maximize Firefox
4. close Firefox
5. start Forefox again

**Expected behavior**
The window corners should be straight just like when you maximize any other window.

**Comment by n4n0GH** [comment]
Can confirm. Logic needs to be adjusted.

**Comment by Acemond** [comment]
Indeed, I checked the code and from what I understood, it's disabling the rounding procedure when it catches a maximize event on the window. It would be ideal to just check whether or not the state of the window is Maximized but unfortunately, KWin::EffectWindow object doesn't have such a property.

**Comment by n4n0GH** [comment]
Quick solution would be to check the size of the new window against the screen's maximized area and if it fits the "is maximized?" criteria, remove rounded corners. Let's see...

**Comment by Acemond** [comment]
Yep looks like a good solution to me, maybe that would even allow riddance of the maximize hook.

**Comment by Acemond** [comment]
Did you try what you wrote here? I was thinking about giving it a shot. What's the latest about this?

**Comment by n4n0GH** [comment]
Well I went as far as to pseudocode the logic which should be in the repo, but haven't started work on this yet. If you want you can try, help is appreciated and welcome!

**Comment by Acemond** [comment]
I see you added a connector to the event &KWin::EffectsHandler::windowAdded.

The problem is that this issue also arise when switching virtual desktops, so I think the window state should be checked during the prepaint method.

I'm looking for a way to check if the window is maximized or not properly. the button applet plasmoids from the dude from latte dock manage to detect the maximized state so I'll check that way.

**Comment by n4n0GH** [comment]
The window decoration checks the state with ```client().data()->isMaximized()``` which returns a bool. Not sure if that'll work for the plugin as well, but might.

**Comment by Acemond** [comment]
I must admit I'm quite new to Cpp development. Coming from Java world I'm lost in symbols. Could you tell me where the f**k does the `client()` symbol comes from?

I'm pretty confident the rounding display logic is the same as the topbar display logic. I mean, I can't point out a case where the bar is shown and the corners are not rounded and the other way around.

**Comment by 143mailliw** [comment]
This seems to just happen randomly for me

**Comment by n4n0GH** [comment]
Can you not reproduce it forcefully by using hello shaders, maximizing a window, closing it and reopening it? It should also have rounded corners even when it was started in maximized mode.

**Comment by 143mailliw** [comment]
Sometimes, when I switch windows, the corners just become rounded again. Doesn't seem to be related to anything else and I couldn't get it to happen consistently.

**Comment by n4n0GH** [comment]
Odd. But still good to know that there are other edgecases.

**Comment by 143mailliw** [comment]
It might be from kwin-lowlatency, but I have no idea why that would happen.

**Comment by 143mailliw** [comment]
@n4n0GH It happens when I toggle maximization on another window, both unmaximizing and maximizing.

**Comment by Acemond** [comment]
I feel obliged to mention that none of that ever happen when you align the rounded corners condition with the property `hasDecoration`. It actually allows to simplify a great deal of code and should be better performance wise than the maximize/minimize hook.

The downside that you mentioned being that you lose rounded corners to not decorated windows (Firefox without title bar). But it's a minority of windows and I feel like it's a better approach rather than rounding everything and adding a lot of exceptions. But I've forked the repo and used it like that and I'm very happy with it, surely I wouldn't be the only one. Maybe that could be a configuration key?

**Comment by n4n0GH** [comment]
It would also affect packages installed by snap, like Spotify. Or anything really that uses GTK.

I'll keep this in mind but honestly I'd rather not downgrade the functionality of the tool. Thank you for pointing it out tho!

**Comment by Acemond** [comment]
It doesn't seem to affect GTK applications, works fine with GIMP and Spotify on my end. Even Wine based windows are rounded correctly.

For now I have listed only three applications that are not compatible on my system: pamac, lutris and firefox (if the titlebar is removed).

I get your point though, the ideal solution would cover all kind of applications that open as a window. It's just that as it is right now, it brings bugs on all windows, minor ones, but still it doesn't feel up to the quality of the rest of your project.

**Comment by n4n0GH** [comment]
I really appreciate the kind words regarding the overall quality of this project. Makes me all giddy :-)

In any case, I haven't really started any work on this toolset and I expect that I'll find some issues I didn't even consider so far. But it'll get there some day.

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
