### ISSUE TITLE
[BUG] The top edge of every window's title bar doesn't match the color set.

### ISSUE THREAD

**Issue by Fennecoonagon** [n4n0GH/hello#18]
**Describe the bug**
I'm not sure whether this is a bug or a feature intended to give windows a 3D look, but seeing how it isn't present in the screenshots found in the README file, I think it isn't supposed to happen.

Here's how I would expect windows to look when stacked on top of another:
![Screenshot_20191118_084055](https://user-images.githubusercontent.com/54739404/69049662-2ae18080-09df-11ea-9ab1-826e9a717ea3.png)
And here's what it looks like when I put a window on top of another that's also got a dark color (notice the brighter shade that contrasts with both the color underneath and the title bar on top of it):
![Screenshot_20191118_084457](https://user-images.githubusercontent.com/54739404/69049930-b6f3a800-09df-11ea-8202-37433f33eeb6.png)

It's more evident when you maximize a window so it makes contact with Latte's panel, set to have the same background color as that window's title bar:
![Screenshot_20191118_085051](https://user-images.githubusercontent.com/54739404/69050315-882a0180-09e0-11ea-943d-0f5c85fcf6d2.png)

I've made sure to disable borders, and the issue persists, so I don't know what could be causing this.

**Comment by n4n0GH** [comment]
This is indeed desired behaviour that was added. I could turn it into a toggle so you can have flat titlebars instead.

**Comment by Fennecoonagon** [comment]
> This is indeed desired behaviour that was added. I could turn it into a toggle so you can have flat titlebars instead.

That would be awesome!

**Comment by n4n0GH** [comment]
Done with ab13f82

**Comment by Fennecoonagon** [comment]
Yup, working perfectly now. Thanks again, you're doing a great job!
