### ISSUE TITLE
[BUG] Heavy flickering when using Compositor > Rendering backend > OpenGL 3.1

### ISSUE THREAD

**Issue by sanderboom** [n4n0GH/hello#19]
**Describe the bug**
Desktop flickering

**To Reproduce**
1. Install and enable all of hello (although this is almost 100% sure caused by Window Decoration component)
2. Make sure  Compositor > Rendering backend  is set to OpenGL 3.1
3. Use the desktop (in the video I just open Kate)
4. Have your treat of stroboscope :boom: 

**Expected behavior**
Less flickering

**Additional files**
(GH doesn't support video files)
[vokoscreen-2019-11-18_12-40-55.zip](https://github.com/n4n0GH/hello/files/3858445/vokoscreen-2019-11-18_12-40-55.zip)

**Additional context**
- Manjaro KDE stable, uptodate
- [kwin-lowlatency](https://github.com/tildearrow/kwin-lowlatency) (also happens with stock kwin)
- Plasma stock panels (no latte-dock)
- Kwin Effects all switched off (also `hello shaders`) besides the minimal I need: 
  - <img width="273" alt="image" src="https://user-images.githubusercontent.com/5956570/69050555-9ab53280-0a02-11ea-80ca-b6150eab2243.png">
- Compositor settings: 
  - <img width="401" alt="image" src="https://user-images.githubusercontent.com/5956570/69050471-693c6700-0a02-11ea-926d-dd1371b2f710.png">
- ... What else would be relevant?

TIA!

**Comment by n4n0GH** [comment]
I can not reproduce this flickering: [2019-11-18 13-04-42.tar.gz](https://github.com/n4n0GH/hello/files/3858481/2019-11-18.13-04-42.tar.gz)

What GPU are you using? On my machine I'm working on integrated Intel graphics with no additional drivers installed.

**Comment by sanderboom** [comment]
> What GPU are you using? On my machine I'm working on integrated Intel graphics with no additional drivers installed.

```
λ inxi -G
Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
           Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting resolution: 2560x1440~60Hz
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) v: 4.5 Mesa 19.2.4
```

Also, subjectively Plasma becomes a bit less responsive with Hello Window Decorations enabled; updating the Window list in panel is slow while navigating Virtual desktops. Very subjective - don't know how to quantify this.

> I can not reproduce this flickering

Could be something on my machine - I mess too much all of everything consistently :stuck_out_tongue_winking_eye: maybe get some more info from others in the mean time...

**Comment by n4n0GH** [comment]
> I mess too much all of everything consistently

Spoken like a true Arch user ;-)

But anyway I'll keep this open and try to reproduce this on other machines.

**Comment by sanderboom** [comment]
> Spoken like a true Arch user ;-)

Keeps me off the streets :sweat_smile: 

> But anyway I'll keep this open and try to reproduce this on other machines.

For me it's back to stock Breeze for now :/ - I'll keep updating and testing now and then. Keep up the good stuff coming!

**Comment by n4n0GH** [comment]
Oh by the way I'm curious: does the bug also happen when you use OpenGL 2.0?

**Comment by sanderboom** [comment]
> Oh by the way I'm curious: does the bug also happen when you use OpenGL 2.0?

Haven't seen it yet!

The lag in updating the Window List when switching Virtual Desktops is definitely higher with hello Window Decorations enabled (also on OpenGL 2.0). Strange to me as the list of windows does not have anything to do with how they are decorated... or does it :thinking: 

Vokoscreen does not do cross-desktop recording, so no video to demonstrate.

**Comment by n4n0GH** [comment]
Which window list are you referring to?

**Comment by sanderboom** [comment]
Ah apparently it's called Task Manager:

<img width="117" alt="image" src="https://user-images.githubusercontent.com/5956570/69057497-49ad3a80-0a12-11ea-99ae-c4698606bca8.png">

I have a panel at the bottom showing widgets Pager + Task Manager:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5956570/69057391-0d79da00-0a12-11ea-946a-f840ddd459d7.png">

The lag I was  referring to is when changing Virtual Desktops the Pager and Task Manager are slow in updating (> 1 second).

**Comment by n4n0GH** [comment]
Thanks. It's something to consider when debugging, as I personally use two workspaces at most and I have no clue how more workspaces affect performance so I'm grateful for the details.

**Comment by sanderboom** [comment]
Update: I've tried SierraBreezeEnhanced window decoration and this does not produce the flickering but does produce the delays (on OpenGL 2.0 and on 3.1). Maybe there is something with rounded corners or shadows that just takes too much time to compute on my GPU. If you know a way to debug / quantify I can test.

**Comment by n4n0GH** [comment]
I don't really know of a good way to debug other than maybe turning on the FPS counter in the desktop effects and then turning the shadows on and off or something?

**Comment by theangryangel** [comment]
FWIW I can reliably reproduce this on both breezewaymod and hello by either (I only use the Window Decorations);
1. Going into Window Decorations settings in System Settings and then switch from hello/breezeway to breeze and back again
2. Altering some options in hello
Until I log out and back in I get heavy and rapid flickering when I mouse over certain controls (usually dropdown/selects)

I havent really had the time to dig in further, mostly because I rarely bother changing my settings once they're dialed in. I only remembered I had this problem when I switched from breezewaymod to hello...

Specs, if it helps.

Arch
Plasma: 5.17.3
Linux: 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000
Nvidia 1080, driver 440.36
Intel i7 9700k

**Comment by n4n0GH** [comment]
I suppose this to be a GPU driver related issue. Some people on Reddit also had issue with flickering on Nvidia and Arch or Arch-based distros. Guess it's time to undust my mini PC and get some Nvidia action going on again :eyes:

**Comment by theangryangel** [comment]
TBH its really not a problem unless you're sat fiddling with options :) Once they're done its rock solid for me.. and looks awesome <3 I'll try and find some time to dig into it one evening, and see if I can help out.

**Comment by n4n0GH** [comment]
Yeah but still it's not really pretty and _could_ lead to some unwanted stuff in the long run. Better to inspect than have y'all download more RAM because memory leaks or something idk.

**Comment by sanderboom** [comment]
> Until I log out and back in I get heavy and rapid flickering

I'll see whether problems are gone after log-out/-in.

This [reddit comment](https://www.reddit.com/r/kde/comments/e1r0sd/plasma_seams_to_slow_down_quite_a_bit_every_3_day/f8roefp/?st=k3hfx0yk&sh=bb377ed3) kind of reminded me of the lag I described. Something in these Breeze derived Window Decorations summons something dark & evil :bat:

**Comment by sanderboom** [comment]
> I'll see whether problems are gone after log-out/-in.

Nope :sob:

**Comment by n4n0GH** [comment]
> Something in these Breeze derived Window Decorations summons something dark & evil
H-Hey now, easy there with the accusations.

Sucks to hear a reboot won't change your situation though. I'll have some more time tomorrow to look into this with a new computer setup running a NVidia configuration on a 980Ti :eyes:

**Comment by arun54321** [comment]
I have flickers when changing themes and it happens when using SBE theme too. I have intel graphics. logout and log in fixes it.

**Comment by n4n0GH** [comment]
Does it only happen when you change themes? What version of Plasma are you running?

**Comment by arun54321** [comment]
> Does it only happen when you change themes? What version of Plasma are you running?

For me, it happens when changing window decorations and also when playing with theme settings. 
Plasma version: 5.17.3 (Arch Linux)

**Comment by n4n0GH** [comment]
I'm beginning to think it might be an issue with Qt...

Time to put on my Sherlock hat I guess.

**Comment by ripefig** [comment]
On Kubuntu 19.10, I get this every time I change the settings in any Breeze-based decoration. It goes away after you restart Kwin. Upstream bug it seems.
It's very useful to have a shortcut bound to restart kwin-x11.

**Comment by n4n0GH** [comment]
I can recomment setting an alias like this: ```alias kre = kwin_x11 --replace > /dev/null 2>&1 &```

This will not print any messages kwin might throw after the replace into the terminal and keep your workspace clean.

**Comment by sanderboom** [comment]
Moar Plasma & flickering: https://www.reddit.com/r/kde/comments/e3l9jz/kde_plasma_desktop_flickering_problem/

> Maybe just have something in readme.md about this issue - probably nothing you can do anyway.

Looks like sth upstream indeed. 

> Time to put on my Sherlock hat I guess.

:muscle:  :raised_hands:

**Comment by n4n0GH** [comment]
From what I understand it's some weird combination of v-sync issues in X11 and slight incompatibility on certain driver/chipset. I'll close the bug for now, but I'd appreciate if you post stuff you find in here anyway because I'm still researching this as well.

**Comment by n4n0GH** [comment]
Started a compiled list of known issues to keep track of everything: https://github.com/n4n0GH/hello/wiki/Known-Problems

**Comment by sowrensen** [comment]
Can confirm the flickering. Setting **Rendering backend** to OpenGL 2.0 seems to resolve it. I didn't notice any flicker after switching to OpenGL 2.0. Using Intel HD Graphics 520.

**Comment by n4n0GH** [comment]
Thank you. This is valuable info. Maybe the bug can be narrowed down to a glitch on OpenGL 3.1 in combination with certain graphics drivers.

**Comment by Schlaefer** [comment]
Back from https://github.com/n4n0GH/breezeway-mod/issues/14#issuecomment-552926814

> Manjaro, Intel HD 620, X here. Same issue: after a the compositor was disabled and enabled again wild flickering starts. But it only happens on the OpenGL 3.1 engine, OpenGL 2.0 and XRender is OK. This is the first time I see any glitches with the OpenGL 3.1 compositor engine.

The problem was easily reproducible for me. https://github.com/kupiqu/SierraBreezeEnhanced showed the same symptoms btw.

The news is: I manually switched to the Intel Gallium3D implementation for Mesa which is supposed the become the default in 2020 [1]. Whatever it was I can't reproduce it anymore and after a few hours it still seems solid.

[1] https://www.phoronix.com/scan.php?page=news_item&px=Mesa-20.0-Default-Build-Iris

**Comment by n4n0GH** [comment]
Hm, in that case I don't think this is something that can be fixed by me without creating some weird hack that will spell incompatibility for future upgrades in driver land.

**Comment by arun54321** [comment]
MESA_LOADER_DRIVER_OVERRIDE=iris fixes this issue.

**Comment by n4n0GH** [comment]
Thanks for sharing you fix! Hopefully someone else will land here due to some Google search and be able to get rid of it as well.

**Comment by sowrensen** [comment]
> MESA_LOADER_DRIVER_OVERRIDE=iris fixes this issue. I don't get glitches after using this.

Yes it worked! I followed [this](https://linuxreviews.org/Intel_Iris) and created a `.driconf` on my home directory. Seems that the flickering is gone when using OpenGL 3.1.

**Comment by arun54321** [comment]
> > MESA_LOADER_DRIVER_OVERRIDE=iris fixes this issue. I don't get glitches after using this.
> 
> Yes it worked! I followed [this](https://linuxreviews.org/Intel_Iris) and created a `.driconf` on my home directory. Seems that the flickering is gone when using OpenGL 3.1.
> 
> **Update**: Well, it was gone for sometime. I did a restart and everything was working perfectly. No more flickering while switching Window Decorations. But then it came back after awhile suddenly when I switched WD again for testing. I am not sure if I set the `MESA_LOADER_DRIVER_OVERRIDE=iris` properly though it worked. So it still could be my fault.

I edited /etc/profile. Added 'export MESA_LOADER_DRIVER_OVERRIDE=iris` and reboot.

**Comment by sowrensen** [comment]
> > > MESA_LOADER_DRIVER_OVERRIDE=iris fixes this issue. I don't get glitches after using this.
> > 
> > 
> > Yes it worked! I followed [this](https://linuxreviews.org/Intel_Iris) and created a `.driconf` on my home directory. Seems that the flickering is gone when using OpenGL 3.1.
> > **Update**: Well, it was gone for sometime. I did a restart and everything was working perfectly. No more flickering while switching Window Decorations. But then it came back after awhile suddenly when I switched WD again for testing. I am not sure if I set the `MESA_LOADER_DRIVER_OVERRIDE=iris` properly though it worked. So it still could be my fault.
> 
> I edited /etc/profile. Added `export MESA_LOADER_DRIVER_OVERRIDE=iris` and reboot. I think it fixes the bug only for Intel igpus. I didn't test on nvidias.

Yes, now it works! Thanks. 😃
