### ISSUE TITLE
[RFC] Move to subprojects

### ISSUE THREAD

**Issue by n4n0GH** [n4n0GH/hello#22]
I received a mail from the maintainer of other popular theme PPAs asking if this project could move to a sub-project based organization, as it'd otherwise apparently be impossible to _just_ get the window decoration into a package on his PPA.

Here's a request for comment, especially from @therealfarfetchd seeing how you made the ebuild for Gentoo. Would the concept that currently exists for the ebuild still work if we'd move to a subproject based git repository?

**Comment by therealfarfetchd** [comment]
I mean, the build file I wrote explicitly allows for disabling everything other than the window decoration, so I don't see the issue here...

But yes, the ebuild would still work. 
Or, since all the different parts of the project are independent of each other, why use submodules at all and not just split it up into different repositories?

**Comment by n4n0GH** [comment]
> why use submodules at all and not just split it up into different repositories?

Hm yes, I might split them up into actual individual repositories but keep the main one as a collection with links to the others.

Do I look like I know what a git is?

**Comment by therealfarfetchd** [comment]
You could also create a GitHub organization, for example 'hello-theme', for all the projects and have the organization page be the page with all the links

**Comment by n4n0GH** [comment]
That's actually something I hadn't considered. Sound choice, I'll look into that during the weekend.

Props for your valuable input once again.

**Comment by krisives** [comment]
+1 for organization and separate repos.

**Comment by n4n0GH** [comment]
Ah yes I'll definitely do that in the future but for the time being I'm thankful you got around the issues you had for packaging.

I'll close this RFC for now and jot it down in the project board to follow up on it at a later point.

Thank you all :pray:
