### ISSUE TITLE
[BUG] Unable to find directory when building all components together.

### ISSUE THREAD

**Issue by baduhai** [n4n0GH/hello#23]
**Describe the bug**
When following instructions to build all components together as listed in the main README.md, a failure occurs when installing.

**To Reproduce**
1. Follow build instructions to the T.
2. See error `file INSTALL cannot find "/home/william/hello/plasma-theme/hello dark".` when running `sudo make install`

**Expected behavior**
Proper build completion and installation.

**Additional files**
[hello_build_error.txt](https://github.com/n4n0GH/hello/files/3882461/hello_build_error.txt)

**Additional context**
Fixed by editing lines 50 & 51 of `[GIT_CLONE_DIR]/build/plasma-theme/cmake_install.cmake` from `"/home/william/hello/plasma-theme/hello dark"` and `"/home/william/hello/plasma-theme/hello light"` to `"/home/william/hello/plasma-theme/hellodark"` and `"/home/william/hello/plasma-theme/hellolight"`. Though I could be wrong and the proper fix would be to add a `\` and have the space be recognised as a character, but the described fix seems to have worked.

**System info**
OS: Arch Linux x86_64  
Kernel: 5.3.12-arch1-1  
CPU: Intel Xeon X5650 (24) @ 2.661GHz  
GPU: AMD ATI Radeon RX 580X  
Memory: 24081MiB

**Comment by n4n0GH** [comment]
Issue arose due to renaming of the individual directories. Should be fixed now, thanks!

**Comment by baduhai** [comment]
That was very quick! Thanks.
