### ISSUE TITLE
[REQ] Window-Specific Override for separator

### ISSUE THREAD

**Issue by krisives** [n4n0GH/hello#24]
**Describe the feature you'd like to see**
Allow a Window-Specific Override setting that provides the same functionality as the `Draw separator between titlebar and window`.

**Comment by n4n0GH** [comment]
That exists already. Check out the "invert global seperator settings" option.

24. Nov. 2019, 20:51 von notifications@github.com:

**Comment by krisives** [comment]
Oh thank you I missed that.
