### ISSUE TITLE
[BUG] Text doesn't update correctly

### ISSUE THREAD

**Issue by Manueljlin** [n4n0GH/hello#27]
**Describe the bug**
When the text is aligned to the left and the titlebar name changes, part of the text doesn't update

**To Reproduce**
1 - Set text alignment to the left
2- Open an app like dolphin and navigate around

**Expected behavior**
Text should display correctly

will try to add more details later

**Comment by n4n0GH** [comment]
I confirmed that to be the case, but I also experience this same behavior on Breeze. Can you confirm this issue appears on regular Breeze on your end as well?

From what I understand something has issues redrawing the title.

**Comment by Manueljlin** [comment]
Yup, also happens with regular Breeze.

**Comment by n4n0GH** [comment]
Glad and sad. At least now I know it wasn't me :eyes:
