### ISSUE TITLE
[BUG] cant download the kwin effect

### ISSUE THREAD

**Issue by joe23reptiles** [n4n0GH/hello#28]
when trying to download the kwin effect via 
git clone https://github.com/n4n0GH/hello/tree/master/kwin-effects && cd kwin-effects

i get the answer 
fatal: repository 'https://github.com/n4n0GH/hello/tree/master/kwin-effects/' not found

**Comment by n4n0GH** [comment]
Oh damn, yeah my bad. So what you have to do is essentially this:

```git clone https://github.com/n4n0GH/hello && cd hello/kwin-effects```

And then you'll be able to build the effect plugin according to the instructions.

**Comment by n4n0GH** [comment]
Updated the README files
