### ISSUE TITLE
Context Help window button has glitched icon

### ISSUE THREAD

**Issue by therealfarfetchd** [n4n0GH/hello#3]
Screenshot: 
![Screenshot](https://i.imgur.com/wZ31AdO.png)

**Comment by n4n0GH** [comment]
After a ton of debugging I still have no clue why the icon is drawn with that weird glitch so I guess say hello (kek) to your new friendly contextual helper icon

![scrot_20191118124421](https://user-images.githubusercontent.com/27410256/69050001-6725d880-0a01-11ea-8fcd-f6198e1689dc.png)
