### ISSUE TITLE
[BUG] white close symbol when using custom colors

### ISSUE THREAD

**Issue by arun54321** [n4n0GH/hello#30]
**Close symbol is white when used with custom button colors**

![image](https://user-images.githubusercontent.com/42943340/69812541-543bb100-1216-11ea-951a-902276baa70e.png)

 **Version**: hello-kde-git-r55.25fe255-1-x86_64 - built from AUR

**Comment by n4n0GH** [comment]
Well, red is a tricky color to calculate luma with. Can you tell me the hex value of that color?

**Comment by n4n0GH** [comment]
Oh also please check if you have any window specific settings going on like forcing bright titlebar fonts.

**Comment by arun54321** [comment]
I'm not using bright font rule for any windows. The color is 255, 48, 75 for close button. I didn't change values for other buttons.

**Comment by arun54321** [comment]
I also tried the color #f36058. It actually bright/light red but I still get that white symbol.

**Comment by n4n0GH** [comment]
Yeah I can confirm this to happen even with my latest repository build. Dangit. I thought I got rid of it once and for all.

I'll take a look at it during the weekend. If you have more colors where that bug appears, please let me know.

**Comment by youssefhabri** [comment]
Would it be possible to just add a way to choose a single color for all buttons?
Like a color for the hover highlight. Otherwise the buttons might have different highlight color for everyone:
![2019-12-31_16-44](https://user-images.githubusercontent.com/1578005/71626586-4f3f9800-2bee-11ea-9aff-aafa422fb97d.png)

**Comment by n4n0GH** [comment]
So the calculation is using very common lumina estimations and calculates the best possible contrast based on that. I need to set up a workaround that doesn't use white as a color or maybe, like suggested, give users an option to override the detection mechanics and force a different calculation.

**Comment by n4n0GH** [comment]
Days of research later and it seems like the calculation I am using is the most accurate one across all different ways of getting "lightness" values in colors. However, purple, green and red seem to have the most inaccurate results as the variation in their values is too damn high.

So to counteract I'll go with the route of letting the user override the method which will be a selection between "brighten all buttons" and "darken all buttons".

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
