### ISSUE TITLE
[REQ] Non-mac button styles

### ISSUE THREAD

**Issue by ripefig** [n4n0GH/hello#31]
**Describe the feature you'd like to see**
Non-mac styles would be useful, especially since they don't really fit the current Breeze style. See https://github.com/kupiqu/SierraBreezeEnhanced for additional styles. It would be especially nice to see a slightly beveled button  style, similar to Gnome Adwaita decorations.

**Comment by n4n0GH** [comment]
No. hello is my personal revisit of macOS' style and as such there's gonna be macOS like buttons.

I have more stuff planned for the future though which is going to be even more flexible than hello so for that theme I might consider that.

My aim is not to compete with the feature set of SBE, but to provide a polished and slick as fuck theme that you won't find anywhere else. I hope you can understand :pray:
