### ISSUE TITLE
[REQ] Option to remove borders for tiled and maximized windows.

### ISSUE THREAD

**Issue by ripefig** [n4n0GH/hello#32]
**Describe the feature you'd like to see**
Latte dock takes on quite a few functions of the window decoration (drag, min, max, close etc). This makes it feasible to hide window decorations without impacting usability too much.

I'd recommend having an option to have very thin borders for maximized and tiled windows, just enough to round out the corners of the window. It saves space and looks very good.

See https://github.com/kupiqu/SierraBreezeEnhanced, which implements thin borders for maximized windows (options: Hide Window Titlebar: Maximized; [x] Allow resizing maximized widnows from window edges). The end result - in @kupiqu's implementation - is basically a rounded  maximized window without a titlebar.

**Comment by n4n0GH** [comment]
I'm not sure I understand you correctly.

You can, at this very moment, set window specific settings and general settings to hide all and every windows' titlebar. Using KDE's settings to select the border width should yield your desired result unless I understood wrong in which case I'd appreciate it if you could provide a screenshot or something to further demonstrate what the endresult should look like.

**Comment by ripefig** [comment]
Like this:
![untitled_page](https://user-images.githubusercontent.com/45201036/69854744-e71e2f00-129a-11ea-9ef6-1e731ce8b77d.png)

SierraBreezeEnhanced does this for maximized windows. Window decoration gets reduced to an outline when a window is maximized.

**Comment by n4n0GH** [comment]
Oh you mean it does that automatically? Huh, that's neat. But it also requires to force unforeseen behaviour (where did my titlebar go?) and reliance on third party software (Latte) to fully work, which makes maintaining this a nightmare in future days to come.

I'd rather not include that in _this_ theme to be honest, but it might be fun for a project I am currently planning.

That's why I'll politely decline your request and close this issue BUT note it down for _that other thing_ ;-)

**Comment by ripefig** [comment]
@n4n0GH What's the project, out of curiousity?

(yeah, it's not a perfect solution, but I find it useful. I think it's logical for this option to be in the window decoration configuration - if you choose to implement this feature of course).

**Comment by n4n0GH** [comment]
The project will be another decoration, but customizable to hell and back.

**Comment by kupiqu** [comment]
> Oh you mean it does that automatically? Huh, that's neat. But it also requires to force unforeseen behaviour (where did my titlebar go?) and reliance on third party software (Latte) to fully work, which makes maintaining this a nightmare in future days to come.

This is an option, so one can have title bars always on, always off, or just off when maximized. Note that this is supported IMO in a weirder way already in kwin and latte. This just makes it easier to configure, nicer to the eye than just removing the titlebar entirely, and keeps the benefits of titlebars, like resizing etc.

You gave me an idea that I may or not implement, that is modifying this setting on/off/max_off with a keyboard shortcut :/

**Comment by n4n0GH** [comment]
I see. Cool stuff. And sorry for giving you ideas I guess ;-)

29. Nov. 2019, 12:37 von notifications@github.com:
