### ISSUE TITLE
[REQ] Maximized windows should not be resizable when dragging from the edges

### ISSUE THREAD

**Issue by 2xsaiko** [n4n0GH/hello#33]
**Describe the bug**
Maximized windows have a border at the top edge that can be used to resize the window. Doing this causes the window to lose the previous non-maximized size.

**To Reproduce**
1. Maximize any window
2. Move cursor to top of the screen
3. Click and drag to resize window

**Expected behavior**
The window should not be able to be resized like this when maximized and should instead only be able to be dragged.

**Bug inheritance**
If the function or feature is also present on KDE's own Breeze theme, does the same bug occur there as well?

It does not.

**Additional context**
distro: Gentoo
hello a39bffa
kwin 5.17.3
plasma-workspace 5.17.3

**Comment by n4n0GH** [comment]
Does that also occur when you de-select the "Draw borders on maximized windows" option?

**Comment by therealfarfetchd** [comment]
It does not.

**Comment by n4n0GH** [comment]
Okay so the "Draw borders on maximized windows" option in the hello settings is the same as the "Allow resizing maximized windows from window edges" setting in Breeze. If you enable that setting in Breeze it should behave just like hello does, can you check if that is the case on your machine as well?

**Comment by therealfarfetchd** [comment]
Yup, seems to have the same effect

**Comment by n4n0GH** [comment]
Okay, then it's expected behavior.

Now, the issue was that windows should not be resizable when in maximized state. I guess I can include a setting to allow/deny this kind of behavior.

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
