### ISSUE TITLE
Missing build dependencies for Fedora

### ISSUE THREAD

**Issue by niklasdoose** [n4n0GH/hello#34]
Hello fellow Hansestädter,

I had the some missing dependencies on Fedora 31:

during configuration:
- Qt5UiTools
- KF5GlobalAccel
- kwineffects.h

solved with `sudo dnf install "cmake(Qt5UiTools)" "cmake(KF5GlobalAccel)" kwin-devel`.

missing to build:
- epoxy/gl.h

solved with `sudo dnf install libepoxy-devel`

After installation of the missing dependencies, the build was succesful!

**Comment by n4n0GH** [comment]
Will add this to the installation instructions. Thanks!
