### ISSUE TITLE
[REQ] Show all button icons when overing a single one

### ISSUE THREAD

**Issue by krisives** [n4n0GH/hello#36]
**Describe the feature you'd like to see**
This is basically a copy of the feature request from SierraBreezeEnhanced [here](https://github.com/kupiqu/SierraBreezeEnhanced/issues/43). When you hover a single button it would show the icons of all the buttons instead of just the one being hovered.

**Additional context**
Currently "hello" has the checkbox in the settings to "Always show button icons" and maybe this could be changed to a dropdown box that has three options:

* Show button icon for single hovered
* Show all icons when any are hovered
* Always show button icons

This would avoid the UI getting confusing IMO.

**Comment by n4n0GH** [comment]
Would make sense, seeing how macOS does it just the same.

**Comment by krisives** [comment]
Keeping up with this issue here is how SBE implemented it: https://github.com/kupiqu/SierraBreezeEnhanced/pull/45/files

**Comment by n4n0GH** [comment]
Thanks, I'll take a look.

**Comment by n4n0GH** [comment]
Hm, the issue that I have with that implementation is that it's not really creating a solid area in which the hover check takes place. This causes a problem when you set up a larger spacing between the buttons and each time your cursor leaves the hover check area which is only available on the buttons themselves plus a little outside padding, the buttons will lose the hover state which can cause a slight flicker if you move over the buttons.

**Comment by krisives** [comment]
I agree. Is there a way to monitor for mouse in/out of the titlebar overall? Then we could calculate min(x) of the button left edges and max(x) of the button right edges and check if the mouseX is between those while in the titlebar.

**Comment by n4n0GH** [comment]
Checking on the entire titlebar isn't necessary in my opinion. I'm currently playing around with using an invisible rectangular area that is only active when the setting for "show all on hover" is turned on. The size can easily be grabbed from the titlebar's constructor for the button area, so that's not the problem.

(Also you'd be delighted to know that I merged the icon settings into a single dropdown)

**Comment by krisives** [comment]
Excellent idea.

On Friday, December 6, 2019, n4n0 <notifications@github.com> wrote:
> Checking on the entire titlebar isn't necessary in my opinion. I'm
currently playing around with using an invisible rectangular area that is
only active when the setting for "show all on hover" is turned on. The size
can easily be grabbed from the titlebar's constructor for the button area,
so that's not the problem.
>
> (Also you'd be delighted to know that I merged the icon settings into a
single dropdown)

**Comment by arun54321** [comment]
Is it possible to delay the symbol disappearing animation by a second or two so it won't flicker?

**Comment by n4n0GH** [comment]
Yes but that would also affect the regular case of moving your mouse away because you don't need the icons anymore. It's not sexy enough to be the solution I want :^)

**Comment by krisives** [comment]
I only want the solution to be so sexy you have to be 18 or older to install the decoration.

**Comment by krisives** [comment]
Thanks I will test this out.

**Comment by krisives** [comment]
Great work. One note for anyone who installs the update it seems you have to restart KWin to get these changes. I tried changing my window decoration and changing it back to kde-hello and it still didn't re-load.

**Comment by n4n0GH** [comment]
I recommend restarting KWin everytime you manually install or update a theme as the caching is quite agressive.

**Comment by krisives** [comment]
It would be neat if we could detect in the decoration settings pane that the loaded version of the decoration isn't the same. This gets back to the IPC problems though and probably needs dbus or similar.

**Comment by n4n0GH** [comment]
I don't think KDE devs even planned for people actually writing Breeze style themes because for Aurorae themes this isn't an issue afaik.

**Comment by krisives** [comment]
When using the [applet-window-buttons](https://github.com/psifidotos/applet-window-buttons) plugin I got this Plasma crash once when I moused over the buttons:

https://gist.github.com/krisives/a63805f9adaef1171248431238387320

Also in that applet the buttons always show their icons even when the mouse isn't hovering anything.

**Comment by n4n0GH** [comment]
Mh yes, I saw that trmdi also found this issue, I'll incorporate his patch later which should fix this.

**Comment by krisives** [comment]
Thanks for all the great work so far.

**Comment by n4n0GH** [comment]
@krisives try if it works with the latest repo.

**Comment by krisives** [comment]
Yup! It works now with `applet-window-buttons` which also got updated to have the object name for detection.
