### ISSUE TITLE
[BUG] outline does not extend to corners when borders set to "none"

### ISSUE THREAD

**Issue by ripefig** [n4n0GH/hello#39]
![image](https://user-images.githubusercontent.com/45201036/70161951-ef78ce80-16cd-11ea-9aae-2b68b4a11a17.png)

This bug is present in KDE's Breeze theme as well.

**Comment by n4n0GH** [comment]
This is appearing while using border radius and no borders and no hello shaders, correct?

**Comment by ripefig** [comment]
this is with no borders.

**Comment by n4n0GH** [comment]
Uh, yes. But you're also using border radius and not using the hello shaders, right?

**Comment by ripefig** [comment]
Ah yes, I didn't see the shaders were an option. I've installed them and it looks good - fixes the issue.

**Comment by ripefig** [comment]
Sorry, didn't mean to close this.

**Comment by n4n0GH** [comment]
Yeah so the reasoning behind this is that the theme itself is expecting borders. At least on the top and bottom to draw the rounded corners.
I actually need to set this up as the "theme suggested border setting". Anyway, when using no borders, the theme still tries to calculate shadows as if it would find rounded corners at the bottom. I _could_ make it so it doesn't look for borders like that, but this is kinda a macOS inspired theme and macOS has rounded corners everywhere.
Maybe for the next project.
If everything worked for you, you are free to close the issue, no worries.
