### ISSUE TITLE
Root CMakeLists.txt?

### ISSUE THREAD

**Issue by therealfarfetchd** [n4n0GH/hello#4]
I'd like to request a root CMakeLists.txt that builds everything at once (including placing the color schemes in /usr/share/color-schemes), preferably with flags to enable/disable building the seperate components. Having that would make it possible to create a single ebuild for Gentoo without making it super hacky.
I'd PR it myself but I know barely anything about cmake.

Thanks!

**Comment by n4n0GH** [comment]
> I'd PR it myself but I know barely anything about cmake.

I concur.

But yes, a single installer for everything would be nice and is planned. Not sure if it's gonna be a single cmake or some bash script, but it'll come once all the things are available to build. Right now I'm mainly missing the application style which I'm working on at the moment.

Let's learn about cmake and make this happen!
