### ISSUE TITLE
[REQ] Find a viable solution to share data between all components

### ISSUE THREAD

**Issue by n4n0GH** [n4n0GH/hello#43]
**Describe the feature you'd like to see**
When users specify a border radius in the window decoration, this new radius should reflect in the effects plugin as well without users having to set it up there manually.

**Additional context**
Things I can maybe use: QSharedPointer, Boost Interprocess

**Comment by krisives** [comment]
Is it possible to load the window decoration config file from the window effect if available?

**Comment by n4n0GH** [comment]
This is something I'm trying to find out. If it's possible, then probably through QSharedPointer.

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
