### ISSUE TITLE
[REQ] Different color for shade button.

### ISSUE THREAD

**Issue by arun54321** [n4n0GH/hello#45]
**Please add different color or custom color option for shade button so it can be differentiated easily.**

![image](https://user-images.githubusercontent.com/42943340/70526953-b8446a80-1b70-11ea-8147-eda5ab57f6e9.png)

**Comment by n4n0GH** [comment]
Holy moly. Okay so this would require a ton of UI changes for the settings. The color selection is long as heck right now, if I were to add four or so more color selections it would get really messy. Nevertheless I understand the reasoning behind this request and will think about how to best get this worked in.

**Comment by arun54321** [comment]
I already implemented this and it is working. Thanks for considering.

**Comment by n4n0GH** [comment]
I know that it will work, what I am concerned about is the settings menu which needs some serious restructuring as the general tab is just way too loaded. That's my only concern really.

**Comment by arun54321** [comment]
I have an another request. Could you make the arrows of shade slightly smaller? Similar to maximize symbol rotated 45 counter clockwise?
![image](https://user-images.githubusercontent.com/42943340/70773865-a47e4b80-1d9e-11ea-8b27-abe72ac37bdf.png)

**Comment by n4n0GH** [comment]
The problem I had with smaller icons on the shade is that it becomes a blurry mess at smaller button sizes. I'd rather see about increasing the size of the maximize button icon.

**Comment by n4n0GH** [comment]
So now you're able to color all buttons individually and I moved the buttons settings to their own tab to uncrowd the settings UI.
