### ISSUE TITLE
Window decorations have unwanted shadow to them

### ISSUE THREAD

**Issue by louisjgeer** [n4n0GH/hello#48]
![Screenshot_20191214_004132](https://user-images.githubusercontent.com/38450537/70844722-7df5fa00-1e0a-11ea-8b3c-e6deabc7c15f.png)

I can't figure out how to get rid of that downwards gradient on the window decorations. I'd like to have the window decorations just one solid color to look more modern. How do i do this?

**Comment by n4n0GH** [comment]
Have you tried using the settings page of the window decoration?

![hellosettings](https://user-images.githubusercontent.com/27410256/70844800-6dfc0b80-1e46-11ea-9284-daea16eb5edc.png)
