### ISSUE TITLE
[BUG] Window Decorations are rendered as an upside down view of the window when window-specific rules are changed

### ISSUE THREAD

**Issue by 143mailliw** [n4n0GH/hello#49]
**Describe the bug**
Window Decorations are rendered as an upside down view of the window when window-specific rules are changed.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to System Settings -> Application Style -> Window Decorations
2. Click on the pencil button under the window decoration
3. Click on Window-Specific Overrides
4. Click add
5. Select a window, and set any custom rule.
6. Click Ok
7. Click Ok
8. See error

**Expected behavior**
The rule is applied with no issues.

**Bug inheritance**
Breeze does not have this issue.

**Additional files**
https://youtu.be/DYDW1X3-HFc 

**Additional context**
Linux william341-arch 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux

**Comment by n4n0GH** [comment]
I am absolutely unable to reproduce your issue. It looks like something else that you have installed on your system is causing this behaviour. What plugins and effects do you have running and what are your compositor settings?

**Comment by arun54321** [comment]
It's a kwin bug. Just restart kwin or logout and login or use opengl 2.0 . It will fix.

**Comment by 143mailliw** [comment]
It's a kwin bug.

**Comment by 143mailliw** [comment]
It also appears to be fairly random if it happens or not, which might be why you can't reproduce it.
