### ISSUE TITLE
[BUG] Installed successfully but no changes

### ISSUE THREAD

**Issue by gvoze32** [n4n0GH/hello#50]
**Describe the bug**
I successfully installed but no changes.

**To Reproduce**
1. Installed
2. Restarted kwin and plasmashell
3. No changes, returned window tab error

**Expected behavior**
Icons and theme changed.

**Additional context**
I'm using latest Manjaro KDE

**Comment by n4n0GH** [comment]
Uh. Die you try selecting the decoration in your KDE settings?

17. Dez. 2019, 14:25 von notifications@github.com:

**Comment by gvoze32** [comment]
What's the name, there's no Hello theme on it

**Comment by n4n0GH** [comment]
Then there must've been something wrong during installation. You said you installed it successfully so I assumed that to be true. 

17. Dez. 2019, 15:42 von notifications@github.com:

**Comment by n4n0GH** [comment]
Please provide logs of your installation and screenshots of your window decoration settings otherwise I'll have to close this as your description is unuseable.

**Comment by gvoze32** [comment]
I try it manually one by one, it works, so may i close this issues
