### ISSUE TITLE
[BUG] cannot build on kubuntu 19.10 (CMAKE Error - Could NOT find KF5)

### ISSUE THREAD

**Issue by HaukeW** [n4n0GH/hello#51]
**Describe the bug**
Hi! I cannot build hello on kubuntu 19.10.

**To Reproduce**
1. I installed the build dependencies (apt install ...) as written on the github-page
2. I followed the Manual Installation
3. I cannot complete the CMAKE-step.

**Expected behavior**
compiling works

**Additional files**
I added the logfile.
[CMakeOutput.log](https://github.com/n4n0GH/hello/files/3994657/CMakeOutput.log)

**Additional context**
distro: kubuntu 19.10

the terminal-output is this:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- Could NOT find KF5Crash (missing: KF5Crash_DIR)
-- Could NOT find KF5Crash: found neither KF5CrashConfig.cmake nor kf5crash-config.cmake 
-- Could NOT find KF5GlobalAccel (missing: KF5GlobalAccel_DIR)
-- Could NOT find KF5GlobalAccel: found neither KF5GlobalAccelConfig.cmake nor kf5globalaccel-config.cmake 
-- Could NOT find KF5KIO (missing: KF5KIO_DIR)
-- Could NOT find KF5KIO: found neither KF5KIOConfig.cmake nor kf5kio-config.cmake 
-- Could NOT find KF5Init (missing: KF5Init_DIR)
-- Could NOT find KF5Init: found neither KF5InitConfig.cmake nor kf5init-config.cmake 
-- Could NOT find KF5Notifications (missing: KF5Notifications_DIR)
-- Could NOT find KF5Notifications: found neither KF5NotificationsConfig.cmake nor kf5notifications-config.cmake 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Crash GlobalAccel KIO Init Notifications)
  (found suitable version "5.65.0", minimum required is "5.9.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  kwin-effects/CMakeLists.txt:37 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by n4n0GH** [comment]
Two things you can try:

1) Install the missing dependencies:
```
sudo apt install build-essential libkf5config-dev libkdecorations2-dev libqt5x11extras5-dev qtdeclarative5-dev extra-cmake-modules libkf5guiaddons-dev libkf5configwidgets-dev libkf5windowsystem-dev libkf5coreaddons-dev gettext
```

2) Use the available PPA which should resolve build dependencies automatically:

```
sudo add-apt-repository ppa:krisives/kde-hello
sudo apt install kde-hello
```

Try either or both and see if it worked out for you.

**Comment by abraha2d** [comment]
Seems to be cmake confused with the KF5 versioning scheme. It thinks 5.65.0 is a lesser version than 5.9.0.

**Comment by abraha2d** [comment]
@n4n0GH some dependencies seem to be missing from that list. I personally needed to install `libkf5crash-dev` and `kinit-dev` in addition to the packages in that list (on KDE Neon 5.17).
@HaukeW try in addition to the dependencies listed, these: `sudo apt install libkf5crash-dev kinit-dev libkf5globalaccel-dev libkf5kio-dev libkf5notifications-dev`

**Comment by n4n0GH** [comment]
Yes that is true, some deps are still missing from the guides. If you feel up to it, feel free to add them and issue a pull request so we can fill in the blanks.

Also @HaukeW you might want to check out this comment https://github.com/n4n0GH/hello/issues/41#issuecomment-562063700 which also lists needed build dependencies for KDE Neon which is essentially just Ubuntu. Those might als help you out as well.

**Comment by HaukeW** [comment]
Thanks everybody, that worked! I installed the dependencies you mentioned and building went through smoothly!

**Comment by YvanKostenevich** [comment]
hey, seems like I've installed all dependencies, but I got weird error:
