### ISSUE TITLE
Dependencies for Opensuse Tumbleweed

### ISSUE THREAD

**Issue by tiwaripramod99** [n4n0GH/hello#52]
I tried installing the app the described way, but I'm unable to get a workaround for dependencies in Opensuse Tumbleweed.

Can anyone help me out with the dependencies?
Thankyou.

**Comment by n4n0GH** [comment]
Sure, can you post the log output for the CMAKE command so I can see what dependencies you're actually missing?

**Comment by tiwaripramod99** [comment]
Following is the output of the cmake command...

➜ build cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for module 'epoxy'
--   Found epoxy, version 1.5.3
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Could NOT find KF5Config (missing: KF5Config_DIR)
-- Could NOT find KF5Config: found neither KF5ConfigConfig.cmake nor kf5config-config.cmake 
-- Could NOT find KF5ConfigWidgets (missing: KF5ConfigWidgets_DIR)
-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
-- Could NOT find KF5CoreAddons (missing: KF5CoreAddons_DIR)
-- Could NOT find KF5CoreAddons: found neither KF5CoreAddonsConfig.cmake nor kf5coreaddons-config.cmake 
-- Could NOT find KF5Crash (missing: KF5Crash_DIR)
-- Could NOT find KF5Crash: found neither KF5CrashConfig.cmake nor kf5crash-config.cmake 
-- Could NOT find KF5GlobalAccel (missing: KF5GlobalAccel_DIR)
-- Could NOT find KF5GlobalAccel: found neither KF5GlobalAccelConfig.cmake nor kf5globalaccel-config.cmake 
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
-- Could NOT find KF5KIO (missing: KF5KIO_DIR)
-- Could NOT find KF5KIO: found neither KF5KIOConfig.cmake nor kf5kio-config.cmake 
-- Could NOT find KF5Service (missing: KF5Service_DIR)
-- Could NOT find KF5Service: found neither KF5ServiceConfig.cmake nor kf5service-config.cmake 
-- Could NOT find KF5Init (missing: KF5Init_DIR)
-- Could NOT find KF5Init: found neither KF5InitConfig.cmake nor kf5init-config.cmake 
-- Could NOT find KF5Notifications (missing: KF5Notifications_DIR)
-- Could NOT find KF5Notifications: found neither KF5NotificationsConfig.cmake nor kf5notifications-config.cmake 
-- Could NOT find KF5Service (missing: KF5Service_DIR)
-- Could NOT find KF5Service: found neither KF5ServiceConfig.cmake nor kf5service-config.cmake 
-- Could NOT find KF5WidgetsAddons (missing: KF5WidgetsAddons_DIR)
-- Could NOT find KF5WidgetsAddons: found neither KF5WidgetsAddonsConfig.cmake nor kf5widgetsaddons-config.cmake 
-- Could NOT find KF5WindowSystem (missing: KF5WindowSystem_DIR)
-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
-- Could NOT find KF5GuiAddons (missing: KF5GuiAddons_DIR)
-- Could NOT find KF5GuiAddons: found neither KF5GuiAddonsConfig.cmake nor kf5guiaddons-config.cmake 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find KF5 (missing: Config ConfigWidgets CoreAddons Crash
  GlobalAccel I18n KIO Service Init Notifications Service WidgetsAddons
  WindowSystem GuiAddons) (Required is at least version "5.9.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  kwin-effects/CMakeLists.txt:37 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pramod/Desktop/hello/build/CMakeFiles/CMakeOutput.log".
See also "/home/pramod/Desktop/hello/build/CMakeFiles/CMakeError.log".

**Comment by tiwaripramod99** [comment]
➜ build cmake -DCMAKE_INSTALL_PREFIX=/usr ..  
-- Could NOT find XCB_XEVIE (missing: XCB_XEVIE_LIBRARY) (found version "")
-- Could NOT find XCB_XPRINT (missing: XCB_XPRINT_LIBRARY) (found version "")
-- didnt find kwineffects.h, not building effects
-- didnt find kwineffects lib, not building effects
-- didnt find kwin glutils lib, not building effects
CMake Error at kwin-effects/CMakeLists.txt:84 (message):
  cant continue


-- Configuring incomplete, errors occurred!
See also "/home/pramod/Desktop/hello/build/CMakeFiles/CMakeOutput.log".
See also "/home/pramod/Desktop/hello/build/CMakeFiles/CMakeError.log".

**Comment by n4n0GH** [comment]
Check if you have the libxcb-devel package installed.

**Comment by tiwaripramod99** [comment]
libxcb-devel is already installed.

**Comment by Raincode** [comment]
I had to add the following. However, consider this list may be incomplete, since I may have already installed some dependencies.

```
zypper install libqt5-qttools-devel libQt5OpenGL-devel libQt5Network-devel
```

But then I realized KDE Frameworks is lower than version 5.9 so I can't build it on Tumbleweed :)

**Comment by n4n0GH** [comment]
Since when is 65 a lower number than 9? I'm a bit confused. As you can see on the screenshot attached, I'm using 5.65 as well and it builds just fine. There must be some other issue that prevents the build from succeeding.
![scrot_20200106194005](https://user-images.githubusercontent.com/27410256/71839853-71d52380-30bc-11ea-94c8-102e8e916b51.png)

**Comment by ryanrms** [comment]
Just set it up.  Besides doing the Fedora command (which returned error: kwin-devel nonexistent)

Added the following packages:


`sudo zypper in libQt5OpenGL-devel kio-devel libQt5Network-devel knotifications-devel kinit-devel kpackage-devel kinit-devel`

This allowed me to build and install using the regular instructions, not sure if this is an exhaustive list of what you need to install.
![Screenshot_20200107_183845](https://user-images.githubusercontent.com/2936638/71943168-f4bdb300-317c-11ea-9163-68f5485cb3da.png)

**Comment by sergiofenoll** [comment]
Also running openSUSE Tumbleweed and encountering the same issue where `XCB_XEVIE` and `CXB_XPRINT` are missing and neither of the `zypper install` commands pulled in the necessary dependencies.

I asked about it on the openSUSE Discord server and apparently those two packages/components (?) were removed from the `libxcb-devel` package and are seemingly not made available through other packages.

**Comment by tiwaripramod99** [comment]
The issue got resolved.

What I found is, XCB_XEVIE & XCB_PRINT are not necessarily required for compiling the app. What I had missing were, kwin-effects related libraries, which once I installed, the app compiled successfully.

Here's a list of libraries I installed,
sudo zypper in libqt5-qtbase-common-devel libQt5Core-devel libQt5Gui-devel libQt5DBus-devel libqt5-qttools-devel libqt5-qtx11extras-devel libQt5OpenGL-devel libQt5Network-devel libepoxy-devel  kcrash-devel kglobalaccel-devel kconfig-devel kconfigwidgets-devel ki18n-devel kio-devel kinit-devel knotifications-devel kguiaddons-devel xcb-util-devel xcb-util-cursor-devel xcb-util-wm-devel xcb-util-keysyms-devel kwindowsystem-devel libKF5WindowSystem5-lang

**Comment by sergiofenoll** [comment]
@tiwaripramod99 is right, although CMake complains that `XCB_XEVIE` and `XCB_XPRINT` could not be found, it still compiles the project. Thanks a lot!

**Comment by Raincode** [comment]
> Since when is 65 a lower number than 9? I'm a bit confused. As you can see on the screenshot attached, I'm using 5.65 as well and it builds just fine. 

You are right, somehow in my mind I read that as 5.6.5... I have the exact same system on a fresh install and have the same errors.

> There must be some other issue that prevents the build from succeeding.

Yes, for example 20 or so packages missing, which I could not find (e. g. the KF5 errors), because I am a noob with KDE :)

I would suggest we add the dependency installation instructions to the README for Tumbleweed, it is very helpful!

**Comment by n4n0GH** [comment]
I'd really appreciate if someone could do a PR with the updated lists as I'm not having as much time working on this anymore so I need to focus on bugs and features. Otherwise it might take some time before the update lands in the actual README.

**Comment by n4n0GH** [comment]
Thanks to @sergiofenoll for creating the PR!
