### ISSUE TITLE
[BUG] Corners shifts color when close to something with color different from current background

### ISSUE THREAD

**Issue by youssefhabri** [n4n0GH/hello#56]
**Describe the bug**
As the title states, the corners will shift color when the window is close to something that has a color different than what's currently under the window

**To Reproduce**
Steps to reproduce the behavior, for example:
1. open a window on a dark background
2. Move the window to something while

**Expected behavior**

**Bug inheritance**
If the function or feature is also present on KDE's own Breeze theme, does the same bug occur there as well?

**Additional files**
If applicable, add screenshots or video to help explain your problem.
![Screenshot_20200104_161125](https://user-images.githubusercontent.com/1578005/71767552-9a6aeb00-2f0d-11ea-9c98-583e030c05d3.png)

![Screenshot_20200104_161150](https://user-images.githubusercontent.com/1578005/71767557-a48ce980-2f0d-11ea-9de2-3c18ac6698e1.png)

**Comment by n4n0GH** [comment]
This only happens when the build defaults are changed and blur is enabled. It's not an issue I can fix since it's a fundamental flaw with KWin. Recompile the theme with default settings and it shouldn't happen.
