### ISSUE TITLE
[REQ] Option to customize the window's corner radius

### ISSUE THREAD

**Issue by evertonstz** [n4n0GH/hello#57]
Add and option to the KWin effect to customize the corner's radius, for me the current radius is too small and I would like to get it a couple pixels bigger! I know I can change it in the window decorations, but it only takes effect in the top radius, the bottom ones stays the old radius value since I think they're no controlled by the window decoration!

**Comment by n4n0GH** [comment]
Yes, that is correct. The radius on the bottom part of the window is controlled by the hello shader plugin which currently has no means of communicating with the window decoration. This is why I opened #43 to find a way to have all of the components share the same data. So if you don't mind I will close this issue and reference it in the other one to keep track of it, but it's essentially a duplicate.
