### ISSUE TITLE
[REQ]Konsole title bar color.

### ISSUE THREAD

**Issue by ovidius72** [n4n0GH/hello#58]
When I use breeze I see that the title bar of the konsole is kinda merged with the window color.
E.g.
![2020-01-05_00-58](https://user-images.githubusercontent.com/3592928/71773041-7da6d580-2f56-11ea-90fc-3d2c84a8fb45.png)

Setting Hello as window decoration there are a lot of improvements about the color and the rounded border but konsole doesn't show anymore the nice merged title bar color.
![2020-01-05_00-55](https://user-images.githubusercontent.com/3592928/71773101-06257600-2f57-11ea-94f1-5a61b40e451b.png)

I've tested both window color and fromcolor scheme in the match color settings with no luck.
Is there anything I can do to preserve the breeze behaviour regarding the konsole title bar color ?
Thanks

**Comment by n4n0GH** [comment]
Have you tried taking a look at the hello window specific settings? You can click the "add" button there and create a new rule set for Konsole to use a different color for the titlebar. Just select any color you want and save.

**Comment by ovidius72** [comment]
Yes I have. Because of the gradient it doesn't render the same as the breeze one, even disabling the gradient setting.

![2020-01-05_10-32](https://user-images.githubusercontent.com/3592928/71777900-0f3e3380-2fa7-11ea-903c-fd4091b6398d.png)

Tried to match the color but it's not the same.

What I'm referring to, most likely is not the original breeze. It has the same name but the setting window offer you the change to disable both window color and color scheme.
Sorry because it's not in English:
![2020-01-05_10-39](https://user-images.githubusercontent.com/3592928/71777974-d0f54400-2fa7-11ea-8a4b-5b3c33a01423.png)
Disabling Match Title Bar's and Window's color result in that effect in konsole. Similar to the iTem2 title bar on Mojave.
Thanks.

**Comment by n4n0GH** [comment]
In the hello settings you go to "Ridefinizioni specifiche per finestra" and click the button on the right with the plus icon that says "add" in your language. In the newly opened window you can do a lot of things that are specific to a certain window, see this screenshot as an example for how my Konsole looks like and what it's settings are:

![scrot_20200105194208](https://user-images.githubusercontent.com/27410256/71784405-797cc580-2ff3-11ea-978e-f7efcfeb58f7.png)

This absolutely will work and if it doesn't there's something really wrong on your system that's preventing this from working. Please try this approach and see if it worked for you.

**Comment by ovidius72** [comment]
Wow. Thanks a lot, it works. I've already been using that setting page but the two checkbox (Invert global....) did the trick.
Fantastic. Thanks again.

**Comment by n4n0GH** [comment]
Glad we got that sorted. Enjoy the theme!
