### ISSUE TITLE
[REQ] Build Dependencies for VoidLinux

### ISSUE THREAD

**Issue by lorenzocarlini** [n4n0GH/hello#64]
I've tried building this theme using the other distro's package lists as a reference but in the end I couldn't find the right package for KF5, could you please add a list for VoidLinux?

**Comment by n4n0GH** [comment]
Uh, I have zero knowledge about VoidLinux or it's packages so I don't think I could. Sorry. Maybe someone with VoidLinux installed is able to tackle this, I'll leave it open for some time.

**Comment by lorenzocarlini** [comment]
I can provide a partial list of everything I needed to compile until that point if that helps

**Comment by n4n0GH** [comment]
Sure! Share whatever you know, it's greatly appreciated.

**Comment by lorenzocarlini** [comment]
For now I managed to figure those out from their repos
`cmake clang gcc extra-cmake-modules qt5-devel kdecoration-devel qt5-declarative-devel qt5-x11extras-devel qt5-tools-dev libepoxy-devel kcoreaddons-devel `
I can't find a devel package for kworkspace (KF5) tho, I hope it helps

**Comment by n4n0GH** [comment]
Looking at https://voidlinux.org/packages/ I don't seem to find those packages either. Can you add custom repositories on Void? Maybe someone else has one where those packages exist?

**Comment by lorenzocarlini** [comment]
It should be possible if I'm not mistaken, I'll check for external repos later and try to find it there.

**Comment by lorenzocarlini** [comment]
Couldn't find that package anywhere, I'm sorry.
I think we'll have to wait for someone to package it.

**Comment by n4n0GH** [comment]
Well, can't be helped then, I guess. I'll close the issue for now but feel free to reopen or open another one once you or someone else finds a way to do this on Void.
