### ISSUE TITLE
[REQ] [hello shaders] don't round Firefox's pip video window

### ISSUE THREAD

**Issue by evertonstz** [n4n0GH/hello#65]
**Describe the feature you'd like to see**
I've not flagged this is a bug, but I think the PIP window should not be rounded on firefox, is that possible at all?

**Comment by n4n0GH** [comment]
Should be possible. I need to update my Firefox to check this though, might be doing that tonight. Who knows ( ͡° ͜ʖ ͡°)

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
