### ISSUE TITLE
[BUG] hello shaders doesn't work well on gtk apps in plasma 5.18

### ISSUE THREAD

**Issue by arun54321** [n4n0GH/hello#66]
![image](https://user-images.githubusercontent.com/42943340/72666543-57466700-3a39-11ea-8481-636f00aa0739.png)

Also affects gtk apps like firefox.

**Comment by n4n0GH** [comment]
Ah, no. The issue here is that the shaders doesn't know what radius you're using for the window borders so it looks off.

**Comment by n4n0GH** [comment]
To elaborate, this is why Issue #43 exists which is supposed to create some sort of API between all components to share a limited degree of information.

**Comment by arun54321** [comment]
I have set the roundness value same on both shader source code and decoration. The bug happens only on 5.18. On plasma 5.17 it works fine. 
![image](https://user-images.githubusercontent.com/42943340/72673586-a7054c80-3a92-11ea-8b0d-2cb2f4a09de9.png)
![image](https://user-images.githubusercontent.com/42943340/72673633-66f29980-3a93-11ea-8544-9d3220ce77ae.png)

**Comment by n4n0GH** [comment]
Mh this is worrysome. I set up a metal machine yesterday with openSUSE Tumbleweed and it is running the the most recent Plasma 5.18 beta. I'll try to compile the theme and shaders for 5.18 next and see about how to fix this.

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
