### ISSUE TITLE
[Plasma Theme] Light theme's colorset too light for Latte dock's "minimized" indicator

### ISSUE THREAD

**Issue by n4n0GH** [n4n0GH/hello#7]
When using a dot or line indicator to show minimized windows, the color is not contrasty enough to be easily seen.

**Comment by psifidotos** [comment]
The minimized indicator in auto created from Latte from the theme's backgroundColor because plasma theme colors do not support such option. Latte understands if the background color is dark or light and accordingly creates a new color which is lightened or darkened. As a reference were used the following themes: Breeze Light/Breeze Dark/Materia

**Comment by n4n0GH** [comment]
Hm, that's interesting to hear. On the same background with the same Plasma theme but different colorschemes the minimized indicator will change color as well:

![latte_light_dark](https://user-images.githubusercontent.com/27410256/68989772-94c92100-084b-11ea-9619-a51c645148bd.png)

It doesn't change behaviour when I change Plasma themes, nor when I switch the Plasma dock from "Smart" to "Plasma" when deciding how it should render colors.

**Comment by psifidotos** [comment]
in your screenshot the first dock I dont see any minimized coloring and the second dock paints it correctly, what do you mean it does not change behavior?

**Comment by n4n0GH** [comment]
> in your screenshot the first dock I dont see any minimized coloring

And this is exactly the problem. The screenshots show the same open and minimized applications, just the colorscheme is different.

On the first screenshot the indicators are white on white background, that's why you can't see them.

**Comment by psifidotos** [comment]
Open a bug report for Latte including materials you used and steps to reproduce in order for me to follow the codepath and check out what breaks

**Comment by n4n0GH** [comment]
Will do that after I tried out some colorscheme modifications. Thanks!

**Comment by n4n0GH** [comment]
Closing this as I most likely won't be working on this any further (see 5f57998e).
