### ISSUE TITLE
Uninstall method?

### ISSUE THREAD

**Issue by Akrai** [n4n0GH/hello#74]
Hi, i installed hello using the script, and i realized it makes the windows corners round even when using another theme
How could i uninstall the theme? Thanks!

**Comment by arun54321** [comment]
Plasma settings  > desktop effects > uncheck hello shaders.

**Comment by n4n0GH** [comment]
Like @arun54321 pointed out, it's not an issue with the theme, but rather the desktop effect you're also installing.
