### ISSUE TITLE
[BUG] Blurred konsole background not cutted by rounded corners

### ISSUE THREAD

**Issue by zezic** [n4n0GH/hello#79]
The corners of a Konsole window have blurry background in transparent areas. The same behavior is noticed when using the default Breeze decorations without the hello shaders, so, probably it is a KDE/KWin bug too.

![Screenshot_20200502_171753](https://user-images.githubusercontent.com/1945127/80866998-755b6e80-8c9a-11ea-99da-d7a3837e9171.png)

**Comment by n4n0GH** [comment]
That's what is called 'blur bleed', a bug due to KWIN not knowing about a decorations possible rounded corners. This is also noted inside the known issues somewhere.

There's nothing I can do about this, sadly, until KDE gets it's shit together.
