### ISSUE TITLE
[Plasma Theme] Light theme and Latte dock, render the "outline" of the dock wrong

### ISSUE THREAD

**Issue by n4n0GH** [n4n0GH/hello#8]
As shown in the screenshot, the right border is rendered weirdly.

![scrot_20191115210608](https://user-images.githubusercontent.com/27410256/68972298-c4e0d780-07eb-11ea-93b1-ffca2a36e24c.png)

**Comment by psifidotos** [comment]
the file you are interested is probably widgets/panel-background.svg the right cropped piece either on mask or main background probably has an 1px. external margin even though it should not

**Comment by n4n0GH** [comment]
Disregard, I was being a dumdum and not using the current version in my local installation while having a working version in the github.
