### ISSUE TITLE
Send to KDE?

### ISSUE THREAD

**Issue by bigbruno** [n4n0GH/hello#82]
Hello, i'm really like your plugin to kwin corner radius.

You tried send to KDE add that plugin officially?

**Comment by n4n0GH** [comment]
Actually there was an ongoing discussion on KDE's Phabricator instance about the evolution of the upstream Breeze theme: https://phabricator.kde.org/T10891
They briefly talked about adding a feature for rounded corners without borders and are probably going to implement it some time. The KWin plugin is also linked in the first post, so the code is no stranger to the developers at KDE.
